(function(){'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ha(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var ja="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ka;
if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var oa=ka;function k(){this.o=!1;this.j=null;this.m=void 0;this.g=1;this.l=this.i=0;this.u=this.h=null}function pa(a){if(a.o)throw new TypeError("Generator is already running");a.o=!0}k.prototype.s=function(a){this.m=a};
function qa(a,b){a.h={N:b,O:!0};a.g=a.i||a.l}k.prototype.return=function(a){this.h={return:a};this.g=this.l};function p(a,b,c){a.g=c;return{value:b}}k.prototype.F=function(a){this.g=a};function ra(a){a.i=0;var b=a.h.N;a.h=null;return b}function sa(a){this.g=new k;this.h=a}function ta(a,b){pa(a.g);var c=a.g.j;if(c)return ua(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return q(a)}
function ua(a,b,c,d){try{var e=b.call(a.g.j,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.o=!1,e;var f=e.value}catch(g){return a.g.j=null,qa(a.g,g),q(a)}a.g.j=null;d.call(a.g,f);return q(a)}function q(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.o=!1,{value:b.value,done:!1}}catch(c){a.g.m=void 0,qa(a.g,c)}a.g.o=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.O)throw b.N;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function va(a){this.next=function(b){pa(a.g);a.g.j?b=ua(a,a.g.j.next,b,a.g.s):(a.g.s(b),b=q(a));return b};this.throw=function(b){pa(a.g);a.g.j?b=ua(a,a.g.j["throw"],b,a.g.s):(qa(a.g,b),b=q(a));return b};this.return=function(b){return ta(a,b)};this[Symbol.iterator]=function(){return this}}function wa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function r(a){return wa(new va(new sa(a)))};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var t=this||self;function xa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ya(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.oa=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function za(a){return a};function v(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var Aa=["ICALENDAR","GOOGLE","WINDOWS_LIVE","YAHOO"],w={ca:"description",ea:"end-date",fa:"end-time",ga:"event-title",LOCATION:"location",ia:"start-date",ja:"start-time",ka:"timezone",ICALENDAR:"icalendar",GOOGLE:"google",WINDOWS_LIVE:"windows-live",YAHOO:"yahoo",BG_COLOR:"bg-color",FONT_COLOR:"font-color",K:"font-family",L:"font-size",M:"font-weight",T:"highlight-color"},Ba={ICALENDAR:"gwd-icalendar-",GOOGLE:"gwd-google-calendar-",WINDOWS_LIVE:"gwd-windows-live-calendar-",YAHOO:"gwd-yahoo-calendar-"},
Ca={ICALENDAR:"iCalendar",GOOGLE:"Google",WINDOWS_LIVE:"Windows Live",YAHOO:"Yahoo"},Da={BG_COLOR:"#fff",FONT_COLOR:"#000",aa:"0px 5px 10px rgba(0, 0, 0, 0.292969)",ba:"0px -5px 10px rgba(0, 0, 0, 0.292969)",K:"arial, helvetica, sans-serif",L:"12pt",M:"normal",ha:"hidden",T:"#e0e0e0",na:"visible"},Ea={X:"background-color",Y:"border-color",Z:"box-shadow",COLOR:"color",da:"display",K:"font-family",L:"font-size",M:"font-weight",la:"top",ma:"visibility"};function Fa(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};var Ga=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var x;function Ha(){if(void 0===x){var a=null,b=t.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:za,createScript:za,createScriptURL:za})}catch(c){t.console&&t.console.error(c.message)}x=a}else x=a}return x};function y(a){this.i=a}y.prototype.toString=function(){return this.i+""};y.prototype.h=!0;y.prototype.g=function(){return this.i.toString()};function Ia(a){return a instanceof y&&a.constructor===y?a.i:"type_error:TrustedResourceUrl"}var Ja={};function Ka(a){var b=Ha();a=b?b.createScriptURL(a):a;return new y(a,Ja)};var La=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ma(){var a=z(),b="";if(B()?"Windows"===C.platform:D("Windows"))b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0";else if(Na()||D("iPad")||D("iPod"))b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".");else if(B()?"macOS"===C.platform:D("Macintosh"))b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10";else if(-1!=z().toLowerCase().indexOf("kaios"))b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1];else if(B()?"Android"===C.platform:D("Android"))b=
/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1];else if(B()?"Chrome OS"===C.platform:D("CrOS"))b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1];a=0;b=La(String(b||"")).split(".");for(var c=La("16").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",g=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;a=Oa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||
Oa(0==f[2].length,0==g[2].length)||Oa(f[2],g[2]);f=f[3];g=g[3]}while(0==a)}return a}function Oa(a,b){return a<b?-1:a>b?1:0};function E(a){this.i=a}E.prototype.toString=function(){return this.i.toString()};E.prototype.h=!0;E.prototype.g=function(){return this.i.toString()};function Pa(a){return a instanceof E&&a.constructor===E?a.i:"type_error:SafeUrl"}var Qa;try{new URL("s://g"),Qa=!0}catch(a){Qa=!1}var Ra=Qa,Sa={},Ta=new E("about:invalid#zClosurez",Sa);var F,G;a:{for(var Ua=["CLOSURE_FLAGS"],H=t,Va=0;Va<Ua.length;Va++)if(H=H[Ua[Va]],null==H){G=null;break a}G=H}var Wa=G&&G[610401301];F=null!=Wa?Wa:!1;function z(){var a=t.navigator;return a&&(a=a.userAgent)?a:""}var C,Xa=t.navigator;C=Xa?Xa.userAgentData||null:null;function Ya(a){return F?C?C.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function D(a){return-1!=z().indexOf(a)};function I(){return F?!!C&&0<C.brands.length:!1}function Za(){return I()?Ya("Chromium"):(D("Chrome")||D("CriOS"))&&!(I()?0:D("Edge"))||D("Silk")};var $a={};function J(a){this.i=a;this.h=!0}J.prototype.g=function(){return this.i.toString()};J.prototype.toString=function(){return this.i.toString()};function ab(a){var b=Ha();a=b?b.createHTML(a):a;return new J(a,$a)};var bb=/^[\w+/_-]+[=]{0,2}$/;function cb(){var a=t.document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&bb.test(a)?a:"":""};/*

 SPDX-License-Identifier: Apache-2.0
*/
function db(a){this.U=a}function K(a){return new db(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var eb=[K("data"),K("http"),K("https"),K("mailto"),K("ftp"),new db(function(a){return/^[^:]*([/?#]|$)/.test(a)})],fb="function"===typeof URL;function gb(a){var b=void 0===b?{}:b;if(a instanceof J)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");b.qa&&(a=a.replace(/(^|[\r\n\t ]) /g,"$1&#160;"));b.pa&&(a=a.replace(/(\r\n|\n|\r)/g,"<br>"));b.ra&&(a=a.replace(/(\t+)/g,'<span style="white-space:pre">$1</span>'));return ab(a)};function hb(a){var b=Ia(ib).toString();if(/#/.test(b))throw Error("");var c=/\?/.test(b)?"&":"?";a.forEach(function(d,e){d=d instanceof Array?d:[d];for(var f=0;f<d.length;f++){var g=d[f];null!==g&&void 0!==g&&(b+=c+encodeURIComponent(e)+"="+encodeURIComponent(String(g)),c="&")}});return Ka(b)};function L(){return window.navigator.userAgent||""};function jb(){return"ontouchstart"in window||0<window.navigator.MaxTouchPoints||0<window.navigator.msMaxTouchPoints};function B(){return F?!!C&&!!C.platform:!1}function Na(){return D("iPhone")&&!D("iPod")&&!D("iPad")};function kb(a){kb[" "](a);return a}kb[" "]=function(){};var lb=D("Gecko")&&!(-1!=z().toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge");function mb(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function nb(a,b){this.type=a;this.target=b}nb.prototype.g=function(){};var ob=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};t.addEventListener("test",c,b);t.removeEventListener("test",c,b)}catch(d){}return a}();function M(a){nb.call(this,a?a.type:"");this.relatedTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.h=null;if(a){var b=this.type=a.type,c=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;var d=a.relatedTarget;if(d){if(lb){a:{try{kb(d.nodeName);var e=!0;break a}catch(f){}e=!1}e||(d=
null)}}else"mouseover"==b?d=a.fromElement:"mouseout"==b&&(d=a.toElement);this.relatedTarget=d;c?(this.clientX=void 0!==c.clientX?c.clientX:c.pageX,this.clientY=void 0!==c.clientY?c.clientY:c.pageY,this.screenX=c.screenX||0,this.screenY=c.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:pb[a.pointerType]||"";this.state=a.state;this.h=a;a.defaultPrevented&&M.I.g.call(this)}}ya(M,nb);var pb={2:"touch",3:"pen",4:"mouse"};M.prototype.g=function(){M.I.g.call(this);var a=this.h;a.preventDefault?a.preventDefault():a.returnValue=!1};var qb="closure_listenable_"+(1E6*Math.random()|0);var rb=0;function sb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.h=e;this.key=++rb;this.g=this.H=!1}function tb(a){a.g=!0;a.listener=null;a.proxy=null;a.src=null;a.h=null};function N(a){this.src=a;this.g={};this.h=0}N.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=ub(a,b,d,e);-1<g?(b=a[g],c||(b.H=!1)):(b=new sb(b,this.src,f,!!d,e),b.H=c,a.push(b));return b};N.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=ub(e,b,c,d);return-1<b?(tb(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};
function ub(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.g&&f.listener==b&&f.capture==!!c&&f.h==d)return e}return-1};var vb="closure_lm_"+(1E6*Math.random()|0),wb={},xb=0;function yb(){function a(c){return b.call(a.src,a.listener,c)}var b=zb;return a}
function Ab(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ab(a,b[f],c,d,e);else if(c=Bb(c),a&&a[qb])a.J(b,c,xa(d)?!!d.capture:!!d,e);else{if(!b)throw Error("Invalid event type");f=xa(d)?!!d.capture:!!d;var g=Cb(a);g||(a[vb]=g=new N(a));c=g.add(b,c,!0,f,e);if(!c.proxy){e=yb();c.proxy=e;e.src=a;e.listener=c;if(a.addEventListener)ob||(d=f),void 0===d&&(d=!1),a.addEventListener(b.toString(),e,d);else if(a.attachEvent)a.attachEvent(Db(b.toString()),e);else if(a.addListener&&a.removeListener)a.addListener(e);
else throw Error("addEventListener and attachEvent are unavailable.");xb++}}}function Db(a){return a in wb?wb[a]:wb[a]="on"+a}
function zb(a,b){if(a.g)a=!0;else{b=new M(b,this);var c=a.listener,d=a.h||a.src;if(a.H&&"number"!==typeof a&&a&&!a.g){var e=a.src;if(e&&e[qb])e.g(a);else{var f=a.type,g=a.proxy;e.removeEventListener?e.removeEventListener(f,g,a.capture):e.detachEvent?e.detachEvent(Db(f),g):e.addListener&&e.removeListener&&e.removeListener(g);xb--;if(f=Cb(e)){g=a.type;var h;if(h=g in f.g){h=f.g[g];var m=Ga(h,a),l;(l=0<=m)&&Array.prototype.splice.call(h,m,1);h=l}h&&(tb(a),0==f.g[g].length&&(delete f.g[g],f.h--));0==
f.h&&(f.src=null,e[vb]=null)}else tb(a)}}a=c.call(d,b)}return a}function Cb(a){a=a[vb];return a instanceof N?a:null}var Eb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Bb(a){if("function"===typeof a)return a;a[Eb]||(a[Eb]=function(b){return a.handleEvent(b)});return a[Eb]};var ib=Ka("");function Fb(){this.port=this.g=null;this.h=[]}Fb.prototype.load=function(){var a=this,b=Gb();this.g=Hb(b);Ib().then(function(){a.g&&document.body.appendChild(a.g)});return Jb(this.g,b).then(function(c){for(a.port=c.ports[0];0<a.h.length;)c=a.h.shift(),a.port.postMessage(c.data,c.V)})};
function Kb(a,b){return new Promise(function(c,d){var e=new MessageChannel;e.port1.onmessage=function(u){e.port1.onmessage=null;u=u.data;null!=u.error?d(new EvalError(u.error)):c(u.result)};for(var f=[],g=[],h=[],m=ha(null!=b?b:[]),l=m.next();!l.done;l=m.next())l=l.value,f.push(l.name),g.push(l.value),l.transfer&&h.push(l.value);f={code:'var url=URL.createObjectURL(blob);var a=document.createElement("a");if(!("download" in a)){throw new Error("Downloading not supported on this browser");}a.href=url;a.download=filename;document.body.appendChild(a);a.click();setTimeout(function(){document.body.removeChild(a);URL.revokeObjectURL(url);},250);',
paramNames:f,values:g};a.port?a.port.postMessage(f,[e.port2].concat(h instanceof Array?h:ia(ha(h)))):a.h.push({data:f,V:[e.port2].concat(h instanceof Array?h:ia(ha(h)))})})}function Gb(){var a=(window.crypto||window.msCrypto).getRandomValues(new Uint8Array(16));return Array.prototype.join.call(a,".")}function Ib(){return new Promise(function(a){"loading"!=document.readyState?a():Ab(document,"DOMContentLoaded",function(){a()})})}
function Jb(a,b){return new Promise(function(c){function d(e){e.source===a.contentWindow&&e.data===b&&(window.removeEventListener("message",d),c(e))}window.addEventListener("message",d)})}
function Hb(a){var b=mb("IFRAME");if(!b.sandbox)throw Error("iframe sandboxes not supported");b.sandbox.value="allow-scripts";b.sandbox.supports&&b.sandbox.add&&b.sandbox.supports("allow-downloads")&&b.sandbox.add("allow-downloads");if(""==ib){a='<!DOCTYPE html><body><input type="hidden" id="nonce" value="'+gb(a)+'" /><script nonce="';var c=cb();a=a+gb(c)+'">var f=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};/*\n\n Copyright The Closure Library Authors.\n SPDX-License-Identifier: Apache-2.0\n*/\nvar h=this||self,k=function(a){return a};var l;var m={},n=function(a){this.g=a};n.prototype.toString=function(){return this.g.toString()};var p=function(a){return a instanceof n&&a.constructor===n?a.g:"type_error:SafeScript"},q=function(a){if(void 0===l){var b=null;var c=h.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:k,createScript:k,createScriptURL:k})}catch(d){h.console&&h.console.error(d.message)}l=b}a=(b=l)?b.createScript(a):a;return new n(a,m)};/*\n\n SPDX-License-Identifier: Apache-2.0\n*/\nfunction r(a,b){a.textContent=p(b);var c,d;(c=(b=null==(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};var t=function(a){var b=f.apply(1,arguments),c,d;"evalCspCompatiblyData"in window||(window.evalCspCompatiblyData={index:0});var e=window.evalCspCompatiblyData.index++;window.evalCspCompatiblyData[e]={args:b,callback:function(g,u){c=g;d=u}};b=document.createElement("script");b.async=!1;b.setAttribute("data-index",e);e=q(\'"use strict";\\v(function(){var idx=parseInt((document.currentScript||Array.prototype.slice.call(document.querySelectorAll("head script[data-index]"),-1)[0]).getAttribute("data-index"),10),curEvalData=evalCspCompatiblyData[idx];delete evalCspCompatiblyData[idx];(function(){var callback=curEvalData.callback;try{callback(true,(\'+\nString(p(a))+"\\n));}catch(ex){callback(false, ex);}}).apply(this, curEvalData.args);})()");r(b,e);e=function(g){c=!1;d=g.error||g};window.addEventListener("error",e);document.head.appendChild(b);window.removeEventListener("error",e);document.head.removeChild(b);if(!c)throw d;return d};var v=document.getElementById("nonce"),w=v?v.value:(new URL(location.href)).searchParams.get("nonce");function x(){if(self.origin)return"null"==self.origin;if(""!=location.host)return!1;try{return window.parent.escape(""),!1}catch(a){return!0}}\n(function(){if(!x())throw"sandboxing error";var a=new MessageChannel;a.port1.onmessage=function(c){try{var d=t.apply(null,[q("(function("+c.data.paramNames.join(", ")+") {\\n"+c.data.code+"\\n}).apply(null, arguments)")].concat(c.data.values));c.ports[0].postMessage({result:d})}catch(e){c.ports[0].postMessage({error:e.toString()})}};var b="*";"chrome-extension:"==location.protocol&&(b=location.origin);window.parent.postMessage(w,b,[a.port2])})();\n\x3c/script></body>';
c=ab(a);a=Ka("data:text/html;charset=UTF-8;base64,"+btoa(c.toString()));b.srcdoc=c instanceof J&&c.constructor===J?c.i:"type_error:SafeHtml"}else a=hb(new Map([["nonce",a]]));b.src=Ia(a).toString();b.style.cssText="height: 0; left: 0; position: absolute; top: 0; width: 0;";b.setAttribute("aria-hidden","true");return b};var O={W:!1},P;function Q(a){this.h=a=void 0===a?O:a;Lb(this.h)||"function"===typeof navigator.msSaveOrOpenBlob||(this.g=new Fb)}Q.download=function(a,b,c,d){c=void 0===c?"":c;d=void 0===d?O:d;return r(function(e){if(1==e.g)return p(e,Mb(a,b,c,d),2);if(e.m)return e.return();P||(P=new Q,Nb());return p(e,Ob(P,a,b,c),0)})};function Nb(){r(function(a){return null==P.g?a.return():p(a,P.g.load(),0)})}
Q.prototype.download=function(a,b,c){c=void 0===c?"":c;var d=this;return r(function(e){return 1==e.g?p(e,Mb(a,b,c,d.h),2):e.m?e.return():p(e,Ob(d,a,b,c),0)})};
function Ob(a,b,c,d){d=void 0===d?"":d;var e,f;return r(function(g){switch(g.g){case 1:e=b instanceof Blob?b:new Blob([b],{type:d});if("function"!==typeof navigator.msSaveOrOpenBlob){g.F(2);break}navigator.msSaveOrOpenBlob(e,c);return p(g,Pb(),3);case 3:return g.return();case 2:if(!(Na()||D("iPad")||D("iPod"))||0<=Ma()||!Za()&&(!D("iPad")&&!D("iPhone")||D("Safari")&&!(Za()||(I()?0:D("Coast"))||(I()?0:D("Opera"))||(I()?0:D("Edge"))||(I()?Ya("Microsoft Edge"):D("Edg/"))||(I()?Ya("Opera"):D("OPR"))||
D("Firefox")||D("FxiOS")||D("Silk")||D("Android"))||Za()||(I()?0:D("Coast"))||D("Firefox")||D("FxiOS")||!D("AppleWebKit"))){g.F(4);break}f=new FileReader;f.onload=function(){var h=mb("A");var m=void 0===m?eb:m;a:{var l=String(f.result);m=void 0===m?eb:m;if(!(l instanceof E)){for(var u=0;u<m.length;++u){var A=m[u];if(A instanceof db&&A.U(l)){l=new E(l,Sa);break a}}l=void 0}}l=l||Ta;if(l instanceof E)var n=Pa(l);else{b:if(fb){try{n=new URL(l)}catch(fc){n="https:";break b}n=n.protocol}else c:{n=document.createElement("a");
try{n.href=l}catch(fc){n=void 0;break c}n=n.protocol;n=":"===n||""===n?"https:":n}n="javascript:"!==n?l:void 0}void 0!==n&&(h.href=n);h.download=c;h.click()};f.readAsDataURL(e);return p(g,Pb(),5);case 5:return g.return();case 4:return null==a.g&&(a.g=new Fb,a.g.load()),p(g,Kb(a.g,[{name:"blob",value:e,transfer:!1},{name:"filename",value:c,transfer:!1}]),6);case 6:return p(g,Pb(),0)}})}
function Mb(a,b,c,d){c=void 0===c?"":c;d=void 0===d?O:d;var e;return r(function(f){switch(f.g){case 1:if(!Lb(d))return f.return(!1);f.i=2;return p(f,Qb(a,b,c),4);case 4:f.g=3;f.i=0;break;case 2:e=ra(f);if(e instanceof DOMException&&"SecurityError"===e.name)return f.return(!1);throw e;case 3:return f.return(!0)}})}function Lb(a){a=void 0===a?O:a;return a.W&&!!window.showSaveFilePicker}
function Qb(a,b,c){c=void 0===c?"":c;var d,e,f,g;return r(function(h){switch(h.g){case 1:var m={suggestedName:b},l;(l=b.match(/\..+$/))?(l=l[0],l=16<l.length?null:l):l=null;if(l){var u={},A=c;A=A.replace(/;[^]*/,"");m.types=[{description:"*"+l,accept:(u[/^\s*[a-zA-Z0-9+._-]+\/[a-zA-Z0-9+._-]+?\s*$/.test(A)?A:"*/*"]=[l],u)}]}d=m;h.i=2;return p(h,window.showSaveFilePicker(d),4);case 4:e=h.m;h.g=3;h.i=0;break;case 2:f=ra(h);if(f instanceof DOMException&&"AbortError"===f.name)return h.return();throw f;
case 3:return p(h,e.createWritable(),5);case 5:return g=h.m,h.i=0,h.l=6,p(h,g.write(a),6);case 6:return h.u=[h.h],h.i=0,h.l=0,p(h,g.close(),9);case 9:m=h.u.splice(0)[0];(m=h.h=h.h||m)?m.O?h.g=h.i||h.l:void 0!=m.F&&h.l<m.F?(h.g=m.F,h.h=null):h.g=h.l:h.g=7;break;case 7:return h.return()}})}function Pb(){return new Promise(function(a){setTimeout(a,500)})}var R=["SafeDownloader"],S=t;R[0]in S||"undefined"==typeof S.execScript||S.execScript("var "+R[0]);
for(var T;R.length&&(T=R.shift());)R.length||void 0===Q?S[T]&&S[T]!==Object.prototype[T]?S=S[T]:S=S[T]={}:S[T]=Q;var Rb=/-|:|\..*\d/g,Sb=/^\D|^$/,Tb=/\d(?=pt|px|em|%)/i,Ub=/8_1_3|8_2/;function Vb(a,b,c,d,e){return c?"https://calendar.yahoo.com/?v=60&title="+a+"&st="+b+"&dur="+c+"&desc="+d+"&in_loc="+e:"https://calendar.yahoo.com/"}
function U(a,b,c){if(!Fa(b,c,{url:a}).detail.handled){if(!(a instanceof E||a instanceof E)){a="object"==typeof a&&a.h?a.g():String(a);b:if(b=a,Ra){try{var d=new URL(b)}catch(e){d="https:";break b}d=d.protocol}else c:{d=document.createElement("a");try{d.href=b}catch(e){d=void 0;break c}d=d.protocol;d=":"===d||""===d?"https:":d}"javascript:"===d&&(a="about:invalid#zClosurez");a=new E(a,Sa)}t.open(Pa(a),"")}}
function Wb(){var a=!jb()&&-1==L().indexOf("Chrome")&&-1!=L().indexOf("WebKit"),b=-1!=L().indexOf("iPad")&&Ub.test(L());return!!window.navigator.msSaveBlob||!a&&!b&&-1==L().indexOf("CriOS")}
function Xb(a,b){if(Wb()){var c=a.D,d=a.v,e=a.A,f=a.description;a=a.location;var g=(new Date).toISOString().replace(Rb,"");Q.download(new Blob(["BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Add To Calendar//\nBEGIN:VEVENT\nUID:"+g+"@*.2mdn.net\nDTSTAMP:"+g+"\nDTSTART:"+d+"\nDTEND:"+e+"\nSUMMARY:"+c+"\nDESCRIPTION:"+f+"\nLOCATION:"+a+"\nEND:VEVENT\nEND:VCALENDAR"],{type:"text/calendar;charset="+document.characterSet}),c+".ics");Fa("icalendar",b)}}
function Yb(a,b){a="&text="+a.D+"&dates="+a.v+"/"+a.A+"&details="+a.description+"&location="+a.location;U(-1==L().indexOf("WebKit")&&-1==L().indexOf("Android")||-1==L().indexOf("Mobile")||-1!=L().indexOf("iPad")?"https://www.google.com/calendar/render?action=TEMPLATE"+a:"https://www.google.com/calendar/gpcal?#~calendar:view=e"+a,"google",b)}
function Zb(a,b){U("https://calendar.live.com/calendar/calendar.aspx?rru=addevent&summary="+a.D+"&dtstart="+a.v+"&dtend="+a.A+"&description="+a.description+"&location="+a.location,"windowslive",b)};var $b=["-ms-","-moz-","-webkit-",""];function V(a,b,c){var d=void 0===d?!1:d;for(var e,f,g=0;g<$b.length;g++)e=$b[g]+b,f=(d?$b[g]:"")+c,a.style.setProperty(e,f)};function W(a,b,c,d){this.u=a;this.B=b;this.C=c;this.h=d;this.m=this.o=this.s=this.l=this.g=null;this.i=["click","touchend"];this.j=Math.random().toString(36).substring(2,6);this.g=document.createElement("div");this.l=this.G.bind(this);this.s=this.S.bind(this);this.o=this.R.bind(this);for(a=0;a<this.C.length;a++)if(c=this.C[a],b=c.className,Wb()||"gwd-icalendar-"!=b)c=document.createTextNode(c.text),d=document.createElement("gwd-taparea"),d.setAttribute("class",b+this.j),d.appendChild(c),d.addEventListener("action",
this.l),jb()||d.addEventListener("mouseover",this.s),d.addEventListener("mouseout",this.o),this.g.appendChild(d);ac(this);this.h.appendChild(this.g);this.m=this.J.bind(this);for(a=0;a<this.i.length;a++)document.body.addEventListener(this.i[a],this.m,!0)}
function bc(a){for(var b=0;b<a.i.length;b++)document.body.removeEventListener(a.i[b],a.m,!0);for(b=a.g.firstChild;b;b=b.nextSibling)b.removeEventListener("action",a.l),b.removeEventListener("mouseover",a.s),b.removeEventListener("mouseout",a.o);a.i.length=0;a.m=null;a.l=null;a.s=null;a.o=null;a.h.removeChild(a.g);a.g=null;a.B=null;a.C=null;a.u=null}
function ac(a){for(var b in Ea){var c=Ea[b];if("visibility"!=c){"background-color"==c||"border-color"==c?b="BG_COLOR":"color"==c&&(b="FONT_COLOR");var d=v(a.h,w[b],Da[b]);"font-size"==c&&(d=Sb.test(d)||Tb.test(d)?d:d+"pt");V(a.g,c,d)}}}
function cc(a,b){var c=a.h.offsetHeight+a.g.offsetHeight+3;c+a.h.offsetTop>a.h.parentElement.clientHeight?(V(a.g,"top","-"+c+"px"),V(a.g,"box-shadow","0px -5px 10px rgba(0, 0, 0, 0.292969)")):(V(a.g,"box-shadow","0px 5px 10px rgba(0, 0, 0, 0.292969)"),a.g.style.removeProperty("top"));V(a.g,"visibility",b?"visible":"hidden")}W.prototype.J=function(a){"visible"==this.g.style.visibility&&(a.preventDefault(),cc(this,!1))};
W.prototype.G=function(a){var b=this.u;switch(a.target.className){case "gwd-icalendar-"+this.j:Xb(b,this.h);break;case "gwd-google-calendar-"+this.j:Yb(b,this.h);break;case "gwd-windows-live-calendar-"+this.j:Zb(b,this.h);break;case "gwd-yahoo-calendar-"+this.j:U(Vb(b.D,b.v,this.B,b.description,b.location),"yahoo",this.h)}};W.prototype.S=function(a){var b=v(this.h,"highlight-color","#e0e0e0");V(a.target,"background-color",b)};W.prototype.R=function(a){a.target.style.removeProperty("background-color")};var dc=[],ec=0,gc;for(gc in w)dc[ec++]=w[gc];function X(){var a=HTMLElement.call(this)||this;a.g=null;a.s=null;a.o=null;a.h=null;a.j=!1;a.i=!1;a.l=!1;a.m=!1;a.C=a.G.bind(a);a.u=!1;return a}var Y=HTMLElement;X.prototype=ja(Y.prototype);X.prototype.constructor=X;if(oa)oa(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var hc=Object.getOwnPropertyDescriptor(Y,Z);hc&&Object.defineProperty(X,Z,hc)}else X[Z]=Y[Z];X.I=Y.prototype;
X.prototype.connectedCallback=function(){if(!this.u){if(0<this.childNodes.length)for(this.s=this.innerHTML;this.firstChild;)this.removeChild(this.firstChild);this.B=document.createElement("gwd-taparea");this.appendChild(this.B);this.u=!0}ic(this);jc(this);this.B.addEventListener("action",this.C)};X.prototype.disconnectedCallback=function(){this.B.removeEventListener("action",this.C);this.h&&(bc(this.h),this.h=null);kc(this)};
X.prototype.attributeChangedCallback=function(a){if(this.u)switch(a){case "description":case "event-title":case "end-date":case "end-time":case "location":case "start-date":case "start-time":case "timezone":ic(this);break;case "icalendar":case "google":case "windows-live":case "yahoo":jc(this);break;case "bg-color":case "font-color":case "font-family":case "font-size":case "font-weight":this.h&&ac(this.h)}};
X.prototype.G=function(){if(this.g){var a=this.i&&!this.j&&!this.l&&!this.m,b=this.l&&!this.j&&!this.i&&!this.m,c=this.m&&!this.j&&!this.i&&!this.l;!this.j||this.i||this.l||this.m?a?Yb(this.g,this):b?Zb(this.g,this):c?(a=this.g,U(Vb(a.D,a.v,this.o,a.description,a.location),"yahoo",this)):this.h&&cc(this.h,!0):Xb(this.g,this)}};function kc(a){a.o=null;a.g=null}
function ic(a){a.g={D:v(a,"event-title",""),description:v(a,"description",""),v:v(a,"start-date",""),A:v(a,"end-date",""),location:v(a,"location",""),startTime:v(a,"start-time",""),endTime:v(a,"end-time",""),P:v(a,"timezone","")};if(""==a.g.D)kc(a);else{""==a.g.A&&(a.g.A=a.g.v);""==a.g.endTime&&(a.g.endTime=a.g.startTime);var b=new Date(a.g.v+" "+a.g.startTime+" "+a.g.P),c=new Date(a.g.A+" "+a.g.endTime+" "+a.g.P);if(isNaN(b)||isNaN(c))kc(a);else if(b.getTime()>c.getTime())kc(a);else{var d=c.getTime()-
b.getTime();var e=Math.floor(d/36E5);d=(Math.floor(d/6E4)-60*e).toString();e=e.toString();2<e.length?e=null:(2>e.length&&(e="0"+e),2>d.length&&(d="0"+d),e+=d);a.o=e;a.s&&(a.g.description=a.s);a.g.v=b.toISOString().replace(Rb,"");a.g.A=c.toISOString().replace(Rb,"");a.h&&(b=a.h,c=a.o,b.u=a.g,b.B=c)}}}
function jc(a){var b=0;a.j=a.hasAttribute("icalendar");a.j&&b++;a.i=a.hasAttribute("google");a.i&&b++;a.l=a.hasAttribute("windows-live");a.l&&b++;a.m=a.hasAttribute("yahoo");a.m&&b++;a.h&&(bc(a.h),a.h=null);if(1<b){b=[];for(var c=0;c<Aa.length;c++){var d=Aa[c];a.hasAttribute(w[d])&&b.push({className:Ba[d],text:Ca[d]})}0!=b.length&&(a.h=new W(a.g,a.o,b,a))}}da.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return dc}}});
customElements.define("gwd-addtocalendar",X);}).call(this);
